# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tideshell Studio
email: contact@tideshell.studio
description: >- # this means to ignore newlines until "baseurl:"
  Tideshell Studio is a small game studio located in Copenhagen, Denmark.
  We make narrative adventure games and other interactive experiences.
address: |
  Pilestræde 43, 1. sal<br>
  1112 Copenhagen<br>
  Denmark
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tideshell.studio" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tideshell
facebook_username:  tideshellstudio
rss: "RSS"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

disqus:
  shortname: tideshell

header_pages:
  - pages/games.md
  - pages/team.md
  - pages/press.md

team_members:
    - name: Sascha
      role: Director, art, design, boss
      image: Sascha.png
      active: yes

    - name: Simon
      role: Technical Lead
      image: Simon.png
      active: yes

    - name: Bjørn
      role: Artist
      image: Bjorn.png
      active: yes

    - name: Bertram
      role: Technical Artist
      image: Bertram.png
      active: yes

    - name: Marco
      role: Animator
      image: Marco.png
      active: no

    - name: Mikkel
      role: Composer
      image: Mikkel.png
      active: no

    - name: Alasdair
      role: Game Designer
      image: Alasdair.png
      active: no

    - name: Søren
      role: Producer
      image: Soren.png
      active: no

    - name: Yasmin
      role: Voice Actor
      image: Yasmin.png
      active: no

    - name: Sally
      role: Voice Actor
      image: Sally.png
      active: no


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
